version: "2"
services:
  app:
    image: tkaaad97/haskell-docker:8.4.3
    command: bash -c 'stack exec cfn-code-gen'
    working_dir: $PWD
    volumes:
      - "$PWD:$PWD"
      - .stack:/root/.stack
